### ISSUE TITLE
shiny.tbeptech.org updated

### ISSUE THREAD

**Issue by esherwoo77** [fawda123/restorebayes#6]
Marcus,
The TBEP shiny server is now updated, and is once again serving the restorebayes ind_eval.Rmd file correctly. The direct link is http://shiny.tbeptech.org/restoreTB/ind_eval.Rmd (let me know if you wanted a different path). Also, I synced the TBEP shiny server's files for this project to this Git repo today.

If you wanted to update the Git files/description/links to this new server address, all should be working fine now.

**Comment by fawda123** [comment]
Thanks Ed, I was messing around with it last week for the water quality dashboard, everything is working, although still a little under-powered
